commit id on aws for multipart was truncated the string returned from amazon in testing is 128 + null term for final length of 129 this was previously truncating the last char resulting in an incorrect id when trying to complete the upload
since there doesnt seem to be any documentation
on how long these could get from aws, double the
previous buffer length to 256 for now

bug:
$ ./s3 -h put testb/test filename=./test
Sending Part Seq 1, length=15728640

ERROR: ErrorNoSuchUpload
  Message: The specified upload does not exist. The upload ID may be
invalid, or the upload may have been aborted or completed.
  Extra Details:
    UploadId:
.yh43YCRYOhfHGAxy_WLPcVAlt.erMiqR2cgv78cdFPPUUa.qiJ.jIvxDlmCHVxyvcLQkztIs6lPmZZyefwl7XJ3gJSQcidWpq80bjxBIGn1NgJ6yUQlUVzrGuqBE2.
    RequestId: 2E96F0D8A8D5CC81
    HostId:
72aAmPpiGcH+gtz/PoZpLRnAA8+1XTxOxLIrznAfRMU8Rj7LObrntPCtpArA1r03S1ubxBjlCAU=

$ s3cmd multipart s3://testb
s3://testb/
Initiated	Path	Id
2015-10-30T17:47:02.000Z	s3://testb/test
.yh43YCRYOhfHGAxy_WLPcVAlt.erMiqR2cgv78cdFPPUUa.qiJ.jIvxDlmCHVxyvcLQkztIs6lPmZZyefwl7XJ3gJSQcidWpq80bjxBIGn1NgJ6yUQlUVzrGuqBE2.r

notice missing "r" from error UploadId above

fix:
$ ./s3 -h put vsm-s3-perf/test filename=./test
Sending Part Seq 1, length=15728640
15712256 bytes remaining (50% complete) ...
...
32768 bytes remaining (99% complete) ...
16384 bytes remaining (99% complete) ...

added test, run tests:
 export S3_ACCESS_KEY_ID="..."
 export S3_SECRET_ACCESS_KEY="..."
 export TEST_BUCKET_PREFIX=vsmlibs3test
 cd test && ./test.sh